In [1]:
import numpy as np

In [9]:
A = np.random.normal(size = (100, 50), scale=10, loc=1)

In [10]:
A

array([[ 15.78816188,   9.06533655,   4.49997424, ...,  11.50442997,
         11.47119301,  22.27229976],
       [ 27.55620893,  -3.46141509,  27.37541765, ...,   4.49121455,
        -13.65402872, -17.21584588],
       [  1.67180813,   1.91830141,  -2.48661996, ..., -10.11413214,
          4.03592619, -17.1109147 ],
       ..., 
       [ -5.33239013,   0.49129714,  -4.76850848, ...,  10.91950291,
         -4.84115236,  -9.52546636],
       [  3.10294384,   4.30781217,   0.69775845, ...,   0.10017749,
          6.09795784,  -3.19814266],
       [ -6.53387459,  16.41151932,  -1.45935167, ...,   1.36294438,
          0.10500248,   3.93972286]])

In [11]:
m = np.mean(A, axis=0)
m

array([ 3.51860248,  0.35628672, -0.31567129,  0.88822234,  0.30978102,
        0.51194694,  1.0331189 ,  1.65362586,  0.01013632,  0.50619604,
        0.02867995,  1.07601504,  1.5527621 ,  1.62336832,  0.46098968,
        3.78376559,  0.70325894,  0.07763421,  2.08728114,  0.77845521,
        0.60983801,  1.4299323 ,  1.90759848,  0.08550572,  2.07752505,
        1.36223873,  1.12747055, -0.40518933,  1.75125871,  0.5062447 ,
        0.77510974,  0.60925622,  1.12368725,  0.49933704,  2.04892429,
       -0.92168684,  1.21988176,  2.82987757,  1.41735162,  0.32454967,
       -0.3355386 ,  1.5722461 ,  1.34524999, -0.10581894,  1.31221545,
        1.48383158, -1.38501474,  0.94496818,  1.78013973,  0.97954042])

In [23]:
A = np.ones(shape=(3,3))

In [24]:
B = np.zeros(shape=(3,3))

In [25]:
A

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [26]:
B

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [28]:
AB = np.vstack((A, B))

In [29]:
AB

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])